### ISSUE TITLE
Semantic analysis of globals - SHOWSTOPPER

### ISSUE THREAD

**Issue by oracleofnj** [ExtendLang/Extend#106]
Going to start working on this right now, but this one is critical! Harass me till it is done if you see this issue still open at noon on Saturday.

**Comment by Neitsch** [comment]
What exactly is the issue? Is semantic analysis on globals missing? Is something going wrong on it?

**Comment by oracleofnj** [comment]
We're not doing it. Try global foo := uddgcfftsfhhcd;

Throws an exception in code gen instead of semantics.

**Comment by oracleofnj** [comment]
Fixed.
