### ISSUE TITLE
Meaningful exceptions

### ISSUE THREAD

**Issue by Neitsch** [ExtendLang/Extend#4]
The compiler and transformer often throw "random" exception that the user does not understand. This should be fixed. This also includes printing line numbers on parsing.

**Comment by oracleofnj** [comment]
This looked like a good starting point at least for handling syntax errors.

http://stackoverflow.com/questions/14046392/verbose-error-with-ocamlyacc

Semantic analysis should eliminate some of the other exceptions we are seeing, for example List.fold_left2 when a function is getting called with the wrong number of arguments; if we check the required number of arguments as part of semantic analysis, we won't get an exception here.

**Comment by oracleofnj** [comment]
Also here (although this might require using Menhir instead of ocamlyacc - not sure)

https://github.com/realworldocaml/examples/blob/master/code/parsing-test/test.ml#L5-L25

**Comment by Neitsch** [comment]
Using menhir will not be a problem, if required.

**Comment by Neitsch** [comment]
@ishaankolluri  did you make any progress on this?

**Comment by ishaankolluri** [comment]
@kevinye1 and I are working on this right now. Will add some new exceptions, and then add illegal extend programs to test such exceptions.
