### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by Neitsch** [ExtendLang/Extend#7]

**Comment by Neitsch** [comment]
What are the components we have to do for this? @ishaankolluri

**Comment by ishaankolluri** [comment]
There's an introduction, a tutorial on how to use our language(compiling and running the program), our language reference manual, our conclusions, reflections, a code listing, and a commit history listing. There's likely a bit more detail, but this is the general essence.

**Comment by Neitsch** [comment]
Could we get started on the final report?

**Comment by ishaankolluri** [comment]
Yup! It's full steam ahead as soon as the PLT Final is over. i'm making it a top priority

**Comment by Neitsch** [comment]
Handled separately.
